# Generated by Django 2.2.3 on 2019-07-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20190709_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='uuid',
            new_name='id',
        ),
    ]
